### ISSUE TITLE
Feature request: option to hide mouse cursor

### ISSUE THREAD

**Issue by protist** [tobiasquinn/gnome-shell-mousewheel-zoom#12]
Hi, I'd very much appreciate the option to hide the mouse cursor when zoomed in. I use zoom for enlarging pictures or videos, primarily, and having the mouse cursor there detracts from that experience. I can imagine the cursor might be useful for others, so perhaps there could be a configuration option?

(Also, as per the other thread, it'd also be great to have the option to change the keybinding from alt to something else, e.g. super, ctrl, etc.)

Cheers.

**Comment by pdostal** [comment]
In #25 I merged the `hidecursor` branch and documented the script.

**Comment by protist** [comment]
Thank you for the fix. Unfortunately I moved to KDE Plasma over five years ago! Good luck with future development though. Cheers! (You can close this issue if you like.)
