### ISSUE TITLE
Feature request: adding the windows key (mod4) option as modifier.

### ISSUE THREAD

**Issue by luigino** [tobiasquinn/gnome-shell-mousewheel-zoom#13]
As per subject, I would love being able to use the same modifier in compiz and gnome-shell/cinnamon.

Granted, one would have to set the overlay_key to something else, but personally I find this arrangement more practical.

**Comment by pdostal** [comment]
I just opened #25 where it should be solved.

**Comment by luigino** [comment]
Thanks, I had forgotten about this.
Unfortunately I've also switched to KDE years ago, so I'm not able to test the solution.

Perhaps someone else could try it?

**Comment by pdostal** [comment]
I use it already for two days and didn't noticed any bug so far. Let's close this :smile:
