### ISSUE TITLE
Upload to extensions.gnome.org ?

### ISSUE THREAD

**Issue by stuaxo** [tobiasquinn/gnome-shell-mousewheel-zoom#15]
Any chance of uploading this to extensions.gnome.org ?

**Comment by prateekmedia** [comment]
Only extensions are uploaded their not a whole application.. :)

**Comment by stuaxo** [comment]
Ooh. silly me assuming this was an extension.

I guess in theory this could be implemented as one, but that is not this.


Thanks for this, with this + libanimation based wobbly windows, I'm only a spinning cube away from the Linux experience I used to enjoy about 15 years ago.
