### ISSUE TITLE
13.10 Version

### ISSUE THREAD

**Issue by akayami** [tobiasquinn/gnome-shell-mousewheel-zoom#17]
Hi, 

This is one of the most useful features/extensions but sadly, it stopped working for me since 13.04.

I've tried to build it from source and I've got exactly the same error in the output as "raring" release is getting on:

https://launchpad.net/~tobias-quinn/+archive/gsmz

I would be very thankful if you could find some time to fix that.

**Comment by pdostal** [comment]
Hello, this is too old and unspecific. Plus there's other issue related to Ubuntu.
