### ISSUE TITLE
Ubuntu 17.10?

### ISSUE THREAD

**Issue by gonzalovinas** [tobiasquinn/gnome-shell-mousewheel-zoom#23]
Hi there, I tried to download from your PPA source but "artful" inst' there. Any changes to add this newly distro BEFORE official "18.04"?  - Thanks in advance!

**Comment by pdostal** [comment]
Hello @gonzalovinas, did you try to compile the project by yourself?

**Comment by gonzalovinas** [comment]
wokring on 18.04.1!! thanks!!  now trying to figure out how to change zooming point..
